version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@biomejs/*"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "vite"
        update-types:
          - "version-update:semver-patch"
